### ISSUE TITLE
argocd always out of sync due to missing public-good keyless url

### ISSUE THREAD

**Issue by chrisjohnson00** [github/artifact-attestations-helm-charts#67]
![image](https://github.com/user-attachments/assets/901f05d8-8c8f-4f9a-98a0-8e581447891c)

Seems the chart is missing the keyless url for `public-good`, and something in my k8s cluster is adding it.  This results in ArgoCD seeing it as out of sync and wanting to remove it... which results in the thing adding it back in.  Vicious vicious cycle ;)

**Comment by codysoyland** [comment]
Fixed by https://github.com/github/artifact-attestations-helm-charts/pull/68
